name: "Build Main"
on:
  push:
    paths:
      - "src/**"
      - "dist/**"
      - "package-lock.json"
      - "package.json"
      - "action.yml"
      - ".github/workflows/build-main.yml"
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: lint
        run: npm run lint:ci
      - name: format check
        run: npm run format:ci
      - name: run tests
        run: npm run test:ci
      - uses: inception-health/otel-upload-test-artifact-action@v1
        if: always()
        with:
          jobName: "lint-and-test"
          stepName: "run tests"
          path: "junit.xml"
          type: "junit"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
  release-please:
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    steps:
      - id: release
        uses: GoogleCloudPlatform/release-please-action@v2
        with:
          token: "${{ secrets.BUILD_PAT }}"
          release-type: node
          package-name: otel-export-trace
