name: "Build Main"
on:
  push:
    paths:
      - "src/**"
      - "package-lock.json"
      - "package.json"
      - "action.yml"
      - ".github/workflows/build-main.yml"
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: lint
        run: npm run lint:ci
      - name: format check
        run: npm run format:ci
      - name: run tests
        run: npm run test:ci
      - uses: inception-health/otel-upload-test-artifact-action@v1
        if: always()
        with:
          jobName: "lint-and-test"
          stepName: "run tests"
          path: "junit.xml"
          type: "junit"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
  update-dist:
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: npm ci
        run: npm ci --omit=dev --ignore-scripts
      - name: tsc
        run: npm run package
      - name: commit dist
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add dist artifacts
          file_pattern: dist
  tag:
    runs-on: ubuntu-latest
    needs: [lint-and-test, update-dist]
    steps:
      - uses: actions/checkout@v2
      - name: autotag
        uses: butlerlogic/action-autotag@stable
        env:
          GITHUB_TOKEN: "${{ secrets.BUILD_PAT }}"
        with:
          strategy: package
          tag_prefix: "v"
